### ISSUE TITLE
Add package support

### ISSUE THREAD

**Issue by JCWasmx86** [lfuelling/cleanfoot#33]
Games often get quite messy with a lot of classes. How about adding support for packages, so you can structure your game?

**Comment by lfuelling** [comment]
Sorry for the late reply, for some reason I was not watching this repo m(

Packages are supported by Java/Maven, not this library. I see no problem with splitting your code in packages with this library.
When using Maven you can even create a parent project with child modules.

See this blog post for more info on how I use this library: https://lerks.blog/making-games-with-greenfoot-without-greenfoot/

Please feel free to reopen this issue in case I've misunderstood.

**Comment by lfuelling** [comment]
Additionally you can use this project as a reference on how to use packages: https://github.com/lfuelling/soultraps
